// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'INDEX',
    'ARCHITECTURE',
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [
        'infrastructure/INDEX',
        'infrastructure/pages/summary',
        'infrastructure/pages/network_architecture',
        'infrastructure/pages/docker_compose',
        'infrastructure/pages/kubernetes',
        'infrastructure/pages/nginx_configuration',
        'infrastructure/pages/tls_certificates',
        'infrastructure/pages/postgresql_architecture',
        'infrastructure/pages/timescaledb_operations',
        'infrastructure/pages/emqx_configuration',
        'infrastructure/pages/authentik_architecture',
        'infrastructure/pages/observability_stack',
        'infrastructure/pages/security_hardening',
        'infrastructure/pages/backup_recovery',
        'infrastructure/pages/scaling_playbook',
        'infrastructure/pages/configuration_reference',
        'infrastructure/pages/troubleshooting',
        'infrastructure/pages/edge_cases',
      ],
    },
    {
      type: 'category',
      label: 'Platform',
      collapsed: true,
      items: [
        'platform/GETTING_STARTED',
        'platform/API_REFERENCE',
        'platform/MQTT_TOPIC_CONTRACT',
        'platform/SECURITY_OVERVIEW',
        'platform/OPERATIONS_RUNBOOK',
        'platform/THROUGHPUT_OPTIMIZATION',
      ],
    },
    {
      type: 'category',
      label: 'Protocol Gateway',
      collapsed: true,
      items: [
        'services/protocol-gateway/INDEX',
        'services/protocol-gateway/pages/summary',
        'services/protocol-gateway/pages/system_overview',
        'services/protocol-gateway/pages/architectural_principles',
        'services/protocol-gateway/pages/layer_architecture',
        'services/protocol-gateway/pages/domain_model',
        'services/protocol-gateway/pages/protocol_adapters',
        'services/protocol-gateway/pages/connection_management',
        'services/protocol-gateway/pages/dataflow_architecture',
        'services/protocol-gateway/pages/resilience_patterns',
        'services/protocol-gateway/pages/observability_infrastructure',
        'services/protocol-gateway/pages/security_architecture',
        'services/protocol-gateway/pages/deployment_architecture',
        'services/protocol-gateway/pages/web_architecture',
        'services/protocol-gateway/pages/device_configuration',
        'services/protocol-gateway/pages/testing_strategy',
        'services/protocol-gateway/pages/standards_compliance',
        'services/protocol-gateway/pages/edge_cases',
        'services/protocol-gateway/pages/appendices',
        'services/protocol-gateway/pages/conclusion',
      ],
    },
    {
      type: 'category',
      label: 'Gateway Core',
      collapsed: true,
      items: [
        'services/gateway-core/INDEX',
        'services/gateway-core/pages/summary',
        'services/gateway-core/pages/system_overview',
        'services/gateway-core/pages/architectural_principles',
        'services/gateway-core/pages/layer_architecture',
        'services/gateway-core/pages/domain_model',
        'services/gateway-core/pages/dataflow_architecture',
        'services/gateway-core/pages/middleware_architecture',
        'services/gateway-core/pages/mqtt_architecture',
        'services/gateway-core/pages/proxy_architecture',
        'services/gateway-core/pages/websocket_bridge',
        'services/gateway-core/pages/resilience_patterns',
        'services/gateway-core/pages/security_architecture',
        'services/gateway-core/pages/observability',
        'services/gateway-core/pages/deployment',
        'services/gateway-core/pages/configuration_reference',
        'services/gateway-core/pages/testing_strategy',
        'services/gateway-core/pages/edge_cases',
        'services/gateway-core/pages/appendices',
      ],
    },
    {
      type: 'category',
      label: 'Data Ingestion',
      collapsed: true,
      items: [
        'services/data-ingestion/INDEX',
        'services/data-ingestion/pages/summary',
        'services/data-ingestion/pages/system_overview',
        'services/data-ingestion/pages/architectural_principles',
        'services/data-ingestion/pages/layer_architecture',
        'services/data-ingestion/pages/domain_model',
        'services/data-ingestion/pages/pipeline_architecture',
        'services/data-ingestion/pages/mqtt_subscriber',
        'services/data-ingestion/pages/writer_internals',
        'services/data-ingestion/pages/database_schema',
        'services/data-ingestion/pages/resilience_patterns',
        'services/data-ingestion/pages/observability',
        'services/data-ingestion/pages/scaling_architecture',
        'services/data-ingestion/pages/performance_tuning',
        'services/data-ingestion/pages/deployment',
        'services/data-ingestion/pages/configuration_reference',
        'services/data-ingestion/pages/testing_strategy',
        'services/data-ingestion/pages/edge_cases',
        'services/data-ingestion/pages/appendices',
      ],
    },
    {
      type: 'category',
      label: 'Web UI',
      collapsed: true,
      items: [
        'services/web-ui/INDEX',
        'services/web-ui/pages/summary',
        'services/web-ui/pages/system_overview',
        'services/web-ui/pages/architectural_principles',
        'services/web-ui/pages/component_architecture',
        'services/web-ui/pages/state_management',
        'services/web-ui/pages/routing_navigation',
        'services/web-ui/pages/auth_architecture',
        'services/web-ui/pages/api_client',
        'services/web-ui/pages/realtime_architecture',
        'services/web-ui/pages/design_system',
        'services/web-ui/pages/performance',
        'services/web-ui/pages/accessibility',
        'services/web-ui/pages/deployment',
        'services/web-ui/pages/configuration_reference',
        'services/web-ui/pages/testing_strategy',
        'services/web-ui/pages/edge_cases',
        'services/web-ui/pages/appendices',
      ],
    },
  ],
};

export default sidebars;
